namespace: fleet-default

helm:

  # Custom values that will be passed as values.yaml to the installation
  values:
    cluster:
      # specify cluster name
      name: template-rke2

    # specify cloud credential secret name, do not need to be provided if using custom driver
    cloudCredentialSecretName: "cattle-global-data:cc-jl6d4"

    # specify cloud provider, options are amazonec2, digitalocean, azure, vsphere or custom
    cloudprovider: "amazonec2"

    kubernetesVersion: "v1.26.13+rke2r1"

    # general RKE options
    rke:
      # enable local auth endpoint
      localClusterAuthEndpoint:
        enabled: false
      # specify fqdn of local access endpoint
      # fqdn: foo.bar.example
      # specify cacert of local access endpoint
      # caCerts: ""

    # specify user principal ids to be assiged as cluster members
    # clusterMembers:
    # - principalName: "local://u-z8zl5"
    #   roleTemplateName: "cluster-member"

    # enable monitoring
    monitoring:
      enabled: false